baseURL = 'https://huing.github.io/'
languageCode = 'zh-cn'
title = 'huingçš„åšå®¢'
theme = 'PaperMod'

defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
hasCJKLanguage = true
paginate = 1000

[author]
  name = "huing"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  env = "production"
  title = "huingçš„åšå®¢"
  description = "huingçš„ä¸ªäººåšå®¢"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "huing"
  DateFormat = "2006-01-02"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  showtoc = true
  tocopen = false
  since = "2020"
  ShowAllPagesInMenu = true # æ·»åŠ æ­¤å‚æ•°æ¥å¯ç”¨æ‰€æœ‰é¡µé¢æ˜¾ç¤º

[params.homeInfoParams]
  Title = "Hi there ğŸ‘‹"
  Content = "Welcome to my blog"

[[menu.main]]
  name = "é¦–é¡µ"
  url = "/post/"
  weight = 10

[[menu.main]]
  name = "æ ‡ç­¾"
  url = "/tags/"
  weight = 20

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/huing"